const legendas = [
    ["🏁", "Aparição"],
    ["🔤", "Alfabética"],
    ["1️⃣", "Número"],
    ["🔘", "Categoria"],
    ["📄", "Página"],
    ["📂", "Subtópico"],
    ["🔗", "Link"],
    ["✅", "Versículo (até 4v) - Integral"],
    ["⚠️", "Atenção (5+v) - Síntese"],
    ["📖", "Leitura (capítulo) - Síntese"],
    ["✝️", "Trecho bíblico"],
    ["💬#️⃣", "Contexto"],
    ["🚩", "Localização"],
    ["📅", "Data"],
    ["#️⃣", "Tags"],
    ["🌏⛺", "Mapa da Lição"],
    ["🌏", "Mapa base"],
    ["🗻", "Região"],
    ["🌏🔗⛺", "Mapa interativo"],
    ["📍", "Marcador"],
    ["⏳", "História"],
    ["🌋", "Geografia"],
    ["🎨", "Arte"],
    ["📝", "Literatura"],
    ["💡", "Filosofia"],
    ["👪", "Sociologia"],
    ["➕", "Matemática"],
    ["⚡", "Física"],
    ["⚛", "Química"],
    ["🌿", "Biologia"],
    ["📘", "Português"],
    ["📙", "Inglês"],
    ["🏃", "Educação Física"],
    ["🎓", "Ano escolar"],
    ["🎯", "Vestibular"],
    ["🔢", "Cronologia"],
    ["❓", "Questões"],
    ["🔑", "Gabaritos"],
    ["📚", "Estudo"],
    ["📜", "Obra"],
    ["🎥", "Filme"],
    ["📖", "Bíblia"],
    ["👑", "Líder/Rei"],  // NOVO
    ["🔤", "Ordenar"],
    ["🏠", "Voltar"],
    ["✅", "Confirmar"],
    ["❌", "Erro"],
    ["⚠️", "Atenção"],
    ["ℹ️", "Informação"],
  ];